logging:
  version: 1
  formatters:
    loggly_formatter:
        format: '{ "time":"%(asctime)s","name":"%(name)s","levelname":"%(levelname)s","lineno":"%(lineno)s","module":"%(module)s","message":"%(message)s"}'

  handlers:
    loggly_handler:
      class: loggly.handlers.HTTPSHandler
      formatter: loggly_formatter
      url: "https://logs-01.loggly.com/inputs/{{ loggly_key }}/tag/gserv"
      level: DEBUG
    state_handler:
      class: loggly.handlers.HTTPSHandler
      formatter: loggly_formatter
      url: "https://logs-01.loggly.com/inputs/{{ loggly_key }}/tag/door_state"
      level: DEBUG      

  root:
    level: DEBUG
    handlers:
      - loggly_handler

  loggers:
    door_state:
      level: INFO
      propagate: False
      handlers:
        - state_handler

mqtt_client_name: ControllerModule
sub_topic: "gserv/#"
input_topic: 'gserv/gpioinput'
open_input: 'open_hall'
close_input: 'close_hall'
hold_input: 'hold'
pir_input: 'pir'
hold_led: 'gserv/gpiooutput/hold_led'
led_topic: 'gserv/leds'
piezo_topic: 'gserv/gpiooutput/piezo'
door_control_topic: 'gserv/gpiooutput/door'
camera_topic: 'gserv/camera'
light_level_topic: 'gserv/sensors/lux'


#PIR Config
# Lux value below which the lights are turned on
min_light_level: 5
light_switch: 'gserv/gpiooutput/light'
# time to wait before processing another PIR event
retrigger_delay: 300
# time to wait from sensed mostion to actually taking the picture
snapshot_delay: 10



