logging:
  version: 1
  formatters:
    loggly_formatter:
        format: '{ "time":"%(asctime)s","name":"%(name)s","levelname":"%(levelname)s","lineno":"%(lineno)s","module":"%(module)s","message":"%(message)s"}'

  handlers:
    loggly_handler:
      class: loggly.handlers.HTTPSHandler
      formatter: loggly_formatter
      url: "https://logs-01.loggly.com/inputs/{{ loggly_key }}/tag/gserv"
      level: DEBUG
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: loggly_formatter

  root:
    level: DEBUG
    handlers:
      - loggly_handler
      - console
mqtt_client_name: ButtonModule
sub_topic: gserv/button/#
buttons:
  - topic: 'gserv/button/close_hall'
    # Pin number in Wiring Pi numberscheme 
    pin: 0
    # Pull Up/Down, can be PUD_UP, PUD_DOWN, PUD_OFF
    pupdown: PUD_OFF
    # Interrupt Edge Trigger type, INT_EDGE_FALLING, INT_EDGE_RISING, INT_EDGE_BOTH, INT_EDGE_SETUP
    edge_type: INT_EDGE_BOTH
    # Debounce time in ms
    debounce: 5
  - topic: 'gserv/button/open_hall'
    pin: 2
    pupdown: PUD_OFF
    edge_type: INT_EDGE_BOTH
    debounce: 5
  - topic: 'gserv/button/pir'
    pin: 3
    pupdown: PUD_OFF
    edge_type: INT_EDGE_RISING
    debounce: 5
  - topic: 'gserv/button/hold'
    pin: 15
    pupdown: PUD_OFF
    edge_type: INT_EDGE_RISING
    debounce: 5