logging:
  version: 1
  formatters:
    mqtt_formatter:
        format: '{ "time":"%(asctime)s","name":"%(name)s","levelname":"%(levelname)s","lineno":"%(lineno)s","module":"%(module)s","message":"%(message)s"}'

  handlers:
    mqtt_handler:
      class: mqtthandler.MQTTHandler
      host: 127.0.0.1
      topic: 'gserv/logger/test_mod'
      qos: 1
      level: INFO
      formatter: mqtt_formatter

  root:
    level: INFO
    handlers: 
      - mqtt_handler

mqtt_client_name: LedsModule
sub_topic: gserv/leds
spi_port: 1
top_led: 2
