logging:
  version: 1
  formatters:
    loggly_formatter:
        format: '{ "time":"%(asctime)s","name":"%(name)s","levelname":"%(levelname)s","lineno":"%(lineno)s","module":"%(module)s","message":"%(message)s"}'

  handlers:
    loggly_handler:
      class: loggly.handlers.HTTPSHandler
      formatter: loggly_formatter
      url: "https://logs-01.loggly.com/inputs/{{ loggly_key }}/tag/gserv"
      level: DEBUG

  root:
    level: INFO
    handlers:
      - loggly_handler

mqtt_client_name: ThingSpeakModule
lux_topic: gserv/sensors/lux
temp_topic: gserv/sensors/temp
hum_topic: gserv/sensors/hum
temp_topic2: gserv/sensors/temp2
hum_topic2: gserv/sensors/hum2
sub_topic: 'gserv/sensors/#'
thingspeak_api_key: {{ thingspeak_key }}